version: "3.8"

services:
  test-db:
    image: postgres:13
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  test-api:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DB_HOST=test-db
      - DB_PORT=5432
      - DB_USER=test_user
      - DB_PASSWORD=test_password
      - DB_NAME=test_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      test-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
